### ISSUE TITLE
[Bug] Custom Mapmarkers not working in certain instances

### ISSUE THREAD

**Issue by Joecuronium** [Bubbus/F3_CA_BUB#140]
**Describe the bug**
User reports, that group mapmarkers changed at runtime get reset on respawn and get be changed again.

**To Reproduce**
Steps to reproduce the behavior (copied from discord):
launch into an mission (e.g. Ace Training).
Change name/symbol/etc. -> this should update on the map
Respawn manually using the default respawn option -> names/symbol/color got reset
Change name/symbol/etc again --> this does not update the map marker

**Expected behavior**
Mapmarker should be changeable by the groupleader at all times.

**Environmental Info(please complete the following information):**
 - V+ 
 - SOG
 - Framework v1.5.0

**Additional context**
Issue filled out by Joecuronium for sniper190, Report not yet confirmed/reproduced.

**Comment by Bubbus** [comment]
Haven't been able to reproduce the marker reset, but have discovered a marker disappearance - this occurs when a player cancels the squad selection menu that appears upon respawn, instead of choosing a squad and clicking "confirm".

Have also discovered sometimes, the squad selection dialog does not appear on respawn.  Really annoying.

**Comment by Bubbus** [comment]
Could not reproduce after applying fixes in this PR - potential resolution here: https://github.com/CombinedArmsGaming/CAFE3/pull/154
