### ISSUE TITLE
[Feature Request] Add support for ACE hunterkiller to the logi vehicle

### ISSUE THREAD

**Issue by Joecuronium** [Bubbus/F3_CA_BUB#142]
**Is your feature request related to a problem? Please describe.**
Vehicles spawned from the logi system do not have ACE_hunterkiller enabled by default (except vanilla)

**Describe the solution you'd like**
Tell logi system when you want to have the system enabled on spawned tanks. This requires applying all brain wrinkles to figure out how Bubbus' macros work and then finding an elegant solution to add Joe's current extremely bad solution.

**Why is this this best way to solve the problem?**
idk, probably a better way somewhere

**Comment by Bubbus** [comment]
Should we be making this into a standard feature?  If so, this is probably best done in `description.ext` with the InitPost event handler, like we do for some of the other stuff.  Add a config toggle for WW2 ops or w/e and we're good.

**Comment by Joecuronium** [comment]
eh, im not sure thats a good idea, if we use the eventhandler some vehicles that might not need it or are configured weirdly may get the system added which could lead to other issues. Unsure how to handle that well.

**Comment by Bubbus** [comment]
Can try it out, I'm not keen on the whitelist idea because it's another thing to configure correctly and get flamed in the AARs about if it's not what some people are expecting.  If we can make it a "thoughtless default" that would be ideal.  If not, then we can look at what is the easiest idea which is actually doable.

**Comment by Joecuronium** [comment]
see, thats the problem, if we just add it to all Tanks, it may not work on some or work weird on others depending on how their base config and turret config is done, so it can also lead to flaming in the aars. may be best to brainstorm this in VC sometime

**Comment by dgibso29** [comment]
Is it feasible to make it a simple toggle like AI Driver? If so, it may address all of the concerns discussed so far, including making it a "thoughtless default."

**Comment by Bubbus** [comment]
An on/off switch is very easy, the part which needs thought is what the default will be.  Default "all on", default whitelist.  Blacklist?
For weirdly configured modded tanks: hunterkiller supports turret path arrays which I do not expect an average MM to be able to write - so do we make FW support for that, or just assume that anyone capable of forming a turret array is capable of editing the desc.ext?  
Blah blah, let's talk about it when it's put into a milestone.

**Comment by Joecuronium** [comment]
alternate solution: give MMs the possibility to run custom code on stuff spawned by the logivic. Provide default hunterkiller code as an example. (its literally a setVariable, so nothing majorly complicated). Folks who know how to custom config stuff will be able to change it themselves. Anyone else will ask us regardless of which solution is implemented if it doesnt work as expected.

**Comment by Bubbus** [comment]
I really like the idea of adding code support to logivic.  I'll copypaste that into a ticket and we'll do it some time soon.

Where I'm coming from: This will be an easy feature to forget, and my focus in the FW is to defend MMs against forgetting.  I already don't really like that for gearscript, pre-placed vics and midgame-spawned ones are treated differently and configured differently - but at least it's obvious if your truck is empty.  This is another thing we can forget to paste into the pre-placed tanks Init field.  I want to have a proper talk about it, to see if there's something clever we can do about this duplicated effort.

Anyway, making this feature available to players is something ACE should be providing support for by itself, instead of making it our problem.  They should also be the ones providing compatibility for mods for their feature.  let's do their work for them lol
