### ISSUE TITLE
[Bug] Modify AI Driver to Reflect new ACE Armour System

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/F3_CA_BUB#68]
AI driver needs an overhaul now that crew can be killed independently of their vehicle.

The current consensus is that making AI Drivers invulnerable is the easiest and best fix for this in the short term.

Further ideas of how to fix this in a more balanced way vs player-driven vehicles are welcome.

**Comment by Bubbus** [comment]
This behaviour should already be implemented - `fn_activateAiDriver` creates a loop that should give the AI driver godmode and also replace the AI driver if it is ever killed.  Will need to reproduce the condition in order to see how this is breaking.

**Comment by Bubbus** [comment]
Bug confirmed - added an AI driver to a T-140 and blasted the crew compartment multiple times with AP and HEAT rounds.  Driver exited the vehicle and fell unconscious with multiple severe injuries.  This is despite being given godmode via the framework function.

I'm going to rewrite this so that if the AI driver exits the vehicle they are immediately replaced.  I'll also add a loop to heal them if needed.  How annoying.
